#!/bin/bash

if [ $# -lt 1 ]
then
cat << HELP

$0  --  list all tags for a container image on a remote registry.

EXAMPLE:
  - list all tags for ubuntu on dockerhub:
      $0 ubuntu

  - list all tags for ubuntu containing "18.04":
      $0 ubuntu 18.04

  - list all tags for an image on a custom registry:
      $0 quay.io/coreos/clair

HELP
fi

REGISTRY="$(echo $1 | cut -d '/' -f 1 -s)"
CONTAINER_PATH="$(echo $1 | cut -d '/' -f 2 -s)"
CONTAINER_NAME="$(echo $1 | cut -d '/' -f 3 -s)"
CONTAINER="$CONTAINER_PATH/$CONTAINER_NAME"

# If there are no forward slashes, we have a single container name
if [ -z ${REGISTRY} ]; then
  REGISTRY="registry.docker.io"
  CONTAINER="library/$1"

# If first part before a slash does not contain a dot, its not a custom registry
elif [[ ! "$REGISTRY" == *"."* ]]; then
  REGISTRY="registry.docker.io"
  CONTAINER_PATH="$(echo $1 | cut -d '/' -f 1 -s)"
  CONTAINER_NAME="$(echo $1 | cut -d '/' -f 2 -s)"
  CONTAINER="$CONTAINER_PATH/$CONTAINER_NAME"

# If there is no third part, we have a container and path
elif [ -z $CONTAINER_NAME ]; then
  REGISTRY="registry.docker.io"
  CONTAINER="$(echo $1 | cut -d '/' -f 1 -s)"
fi

TOKEN="$(curl --silent --get --data-urlencode "service=${REGISTRY}" --data-urlencode "scope=repository:${CONTAINER}:pull" "https://auth.docker.io/token" | jq --raw-output '.token')"

if [ $REGISTRY == "registry.docker.io" ]; then
  TAGS="$(wget -q --header "Accept: application/json" --header "Authorization: Bearer $TOKEN" "https://registry-1.docker.io/v2/${CONTAINER}/tags/list" -O - | tr ',' '\n' | tr -d '{}[]"' | tail -n +3)"
else
  TAGS=`wget -q https://"$REGISTRY"/v1/repositories/${CONTAINER}/tags -O - | tr ',' '\n' | sed 's/[}{]//g' | cut -d: -f1 | tr -d '"'`
fi

if [ -z "$TAGS" ]
then
  echo "No tags found for container ${CONTAINER}, please check that the image name is correct."
  echo "NOTE: the 'library/' path is automatically added to single-name images such as 'alpine'."
  exit 1
fi

if [ -n "$2" ]
then
  TAGS=` echo "${TAGS}" | grep "$2" `
  echo "${TAGS}"
else
  echo "${TAGS}"
fi
